---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define __mariadb_home
  set_fact:
    tomcat7_home: "{{ __mariadb_home }}"
  when: tomcat7_home is not defined


