---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define __mariadb_home
  set_fact:
    mariadb_home: "{{ __mariadb_home }}"
  when: mariadb_home is not defined


