---
# This playbook will install MariaDB and create db user and give permissions.

- name: example copying file with owner and permissions
  unarchive:
    src: "{{ __src_tarfile }}"
    dest: /usr/local
    copy: yes
    owner: root
    group: root
    mode: 0644


# tar Extract archive
# group, user add
# group, owner change
# Mysql Configuration file make
### mariadb install


- name: Simbolic link
  file:
    src: "{{ __mariadb_src }}"
    path: "{{ __mariadb_home }}"
    state: link
  become: yes

- name: groupadd
  command: groupadd mysql

- name: useradd
  command: useradd -g mysql mysql

- name: mysql folder owner change
  command: chdir={{ __mariadb_home }} chown -R mysql .

- name: mysql folder group change
  command: chdir={{ __mariadb_home }} chgrp -R mysql .

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb
## ncurse / libaio-dev
## 템플릿 UBU
## permission denied
# 자동생성인듯? 의심
- name: Create MariaDB log file
  command: chdir=/var/log touch mysqld.log

- name: make files chmod 0755
  command: chdir=/var/log chmod 755 mysqld.log

- name: chown Directory
  command: chdir=/var/log chown mysql mysqld.log

- name: chgrp Directory
  command: chdir=/var/log chgrp mysql mysqld.log

- name: make Directory
  command: chdir=/var/lib mkdir mysql

- name: Create MariaDB pid file
  command: chdir={{ __pid }} touch mysqld.pid
- name: make files chmod 0755
  command: chdir={{ __pid }} chmod 755 mysqld.pid

- name: chown Directoryexit
  command: chdir=/var/lib/ chown mysql mysql

- name: chgrp Directory
  command: chdir=/var/lib/ chgrp mysql mysql

- name: chmod Directory
  command: chdir=/var/lib chmod 755 mysql

- name: make files 0644
  command: find {{ __mariadb_home }}/bin/ -type f ! -perm 0755 -exec chmod 0755 {} \;

- name: make files 0644
  command: find {{ __mariadb_home }}/scripts/ -type f ! -perm 0755 -exec chmod 0755 {} \;

- name: mysql_install
  command: chdir={{ __mariadb_home }} ./scripts/mysql_install_db --user=mysql --defaults-file=/etc/my.cnf

- name: Delete ibdata.*
  command: chdir=/var/lib/mysql/ rm -rf ib*

## mysql 설치후 엔터를 쳐야되는데,, 엔터가 안쳐져서 문제 해결방법은?

- name: Service script
  command: /bin/cp /usr/local/mysql/support-files/mysql.server /etc/init.d/mysqld

- name: Permission
  command: chdir=/etc/init.d/ chmod 755 mysqld

- name: Permission
  command: chdir=/etc/init.d/ chown mysql mysqld

- name: Permission
  command: chdir=/etc/init.d/ chgrp mysql mysqld

- name: enable service 1
  command: /etc/init.d/mysqld start

- name: enable service 2
  command: chkconfig --add mysqld
- name: enable service 3
  command: chkconfig mysqld on

- name: reboot
  command: reboot
## mysql 설치후 엔터를 쳐야되는데,, 엔터가 안쳐져서 문제 해결방법은?