# yum install -y gcc / gcc ++ / make / pcre-devel
# apr / apr-util / pcre / httpd .tar.gz 준비



- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/httpd-2.2.15.tar.gz
    dest: /opt/httpd-2.2.15.tar.gz
    owner: root
    group: root
    mode: 0644
- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/apr-1.7.0.tar.gz
    dest: /opt/apr-1.7.0.tar.gz
    owner: root
    group: root
    mode: 0644
- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/apr-util-1.6.1.tar.gz
    dest: /opt/apr-util-1.6.1.tar.gz
    owner: root
    group: root
    mode: 0644
- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/pcre-8.41.tar.gz
    dest: /opt/pcre-8.41.tar.gz
    owner: root
    group: root
    mode: 0644

### tar unarchive

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/httpd-2.2.15.tar.gz -C /opt/ creates=/opt/httpd-2.2.15

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apr-1.7.0.tar.gz -C /opt/ creates=/opt/apr-1.7.0

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apr-util-1.6.1.tar.gz -C /opt/ creates=/opt/apr-util-1.6.1

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/pcre-8.41.tar.gz -C /opt/ creates=/opt/pcre-8.41

### mv /usr/local/apache

- name: mkdir
  command: chdir=/usr/local/ mkdir apache

- name: mv folder to /usr/local/apache
  command: chdir=/opt/ mv httpd-2.4.46/ /usr/local/apache

- name: mv folder to /usr/local/apache
  command: chdir=/opt/ mv apr-1.7.0/ /usr/local/apache

- name: mv folder to /usr/local/apache
  command: chdir=/opt/ mv apr-util-1.6.1/ /usr/local/apache

- name: mv folder to /usr/local/apache
  command: chdir=/opt/ mv pcre-8.41/ /usr/local/apache

### install / compile

- name: configure
  command: chdir=/usr/local/apache/apr-1.7.0 ./configure

- name: make, make install
  command: chdir=/usr/local/apache/apr-1.7.0/ make && make install