---

## OS 정해주는 task


- name: Include distribution dependent variables
  include_vars: apache.yml
  tags: apache

- name: Install Apache2, Configure Apache2
  include_tasks: total.yml
  tags: apache
