# yum install -y gcc / gcc ++ / make / pcre-devel
# apr / apr-util / pcre / httpd .tar.gz 준비
- name: pcre-devel
  yum: name=pcre-devel state=present


- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/httpd-2.4.48.tar.gz
    dest: /opt/httpd-2.4.48.tar.gz
    owner: root
    group: root
    mode: 0644
- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/apr-1.7.0.tar.gz
    dest: /opt/apr-1.7.0.tar.gz
    owner: root
    group: root
    mode: 0644
- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/apr-util-1.6.1.tar.gz
    dest: /opt/apr-util-1.6.1.tar.gz
    owner: root
    group: root
    mode: 0644
- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/pcre-8.41.tar.gz
    dest: /opt/pcre-8.41.tar.gz
    owner: root
    group: root
    mode: 0644

### tar unarchive

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/httpd-2.4.48.tar.gz -C /opt/ creates=/opt/httpd-2.4.48

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apr-1.7.0.tar.gz -C /opt/ creates=/opt/apr-1.7.0

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apr-util-1.6.1.tar.gz -C /opt/ creates=/opt/apr-util-1.6.1

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/pcre-8.41.tar.gz -C /opt/ creates=/opt/pcre-8.41




### install / compile apr / apr-util

### yum install expat-devel 파일 반입 필요

- name: yum install expat-devel
  yum: name=expat-devel state=present

- name: configure
  command: chdir=/opt/apr-1.7.0 ./configure --prefix=/usr/local/apr-1.7.0

- name: make, make install
  command: chdir=/opt/apr-1.7.0 make
- name: make install
  command: chdir=/opt/apr-1.7.0 make install

- name: configure
  command: chdir=/opt/apr-util-1.6.1 ./configure --prefix=/usr/local/apr-util-1.6.1 --with-apr=/usr/local/apr-1.7.0

- name: make, make install
  command: chdir=/opt/apr-util-1.6.1 make
- name: make, make install
  command: chdir=/opt/apr-util-1.6.1 make install


  # cd /usr/local/src/pcre-8.41

  # ./configure --prefix=/usr/local/src/apr-util-1.6.1 --with-apr=/usr/local/src/apr-1.6.3

  # make && make install

- name: configure
  command: chdir=/opt/pcre-8.41 ./configure --prefix=/usr/local/pcre-8.41

- name: make && make install
  command: chdir=/opt/pcre-8.41 make
- name: make && make install
  command: chdir=/opt/pcre-8.41 make install




  # cd /usr/local/src/httpd-2.4.29

  # ./configure --prefix=/usr/local/apache2 --enable-modules=most --enable-mods-shared=all --enable-so --with-apr=/usr/local/src/apr-1.6.3 --with-apr-util=/usr/local/src/apr-util-1.6.1

  # make &&  make install

- name: configure
  command: chdir=/opt/httpd-2.4.48 ./configure --prefix=/usr/local/apache2 --with-apr=/usr/local/apr-1.7.0 --with-apr-util=/usr/local/apr-util-1.6.1
    #--with-apr=/usr/local/apr --with-apr-util=/usr/local/apr-util

- name: make && make install
  command: chdir=/opt/httpd-2.4.48 make

- name: make && make install
  command: chdir=/opt/httpd-2.4.48 make install


- name: Update?  Mysql configuration file
  template: src=httpd.conf dest=/usr/local/apache2/conf/httpd.conf

## service

- name: service start
  command: chdir=/usr/local/apache2/bin/httpd -k start
