- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/httpd-2.2.15.tar.gz
    dest: /opt/httpd-2.2.15.tar.gz
    owner: root
    group: root
    mode: 0644

    # yum install -y gcc / gcc ++ / make / pcre-devel
    # apr / apr-util / pcre / httpd .tar.gz 준비
    #
    #
    #
    #
    #
