- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/httpd-2.2.15.tar.gz
    dest: /opt/httpd-2.2.15.tar.gz
    owner: root
    group: root
    mode: 0644


    # ./configure --prefix=/usr/local/apache2 --enable-modules=most --enable-mods-shared=all --enable-so --with-apr=/usr/local/apache/apr-1.7.0 --with-apr-util=/usr/local/apache/apr-util-1.6.1
    #
    #
    #
    #
    #
