---
# This playbook will install MariaDB and create db user and give permissions.

- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/mariadb-10.3.20.tar.gz
    dest: /opt/mariadb-10.3.20.tar.gz
    owner: root
    group: root
    mode: 0644


- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/mariadb-10.3.20.tar.gz -C /opt/ creates=/opt/mariadb-10.3.20

### mariadb install

- name: Symbolic link
  command: ln -s /opt/mariadb-10.3.20 /usr/local/maria

- name: groupadd, useradd
  command: groupadd mysql; useradd -g mysql mysql

- name: mysql folder owner change
  command: chdir=/usr/local/maria chwon -R mysql .

- name: mysql folder group
  command: chdir=/usr/local/maria chgrp -R mysql .





- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mariadb

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: insert firewalld rule
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
