---
- name: Include distribution dependent variables
  with_first_found:
    - "{{ ansible_os_family }}.yml"
  tags: mariadb

- name: Install MariaDB, Configure MariaDB
  include_tasks: total.yml
  tags: mariadb
