---
## tomcat /bin/실행파일 가져오기
## restart tomat9 명령어noti

- name: server configuration
  template:
    src: server.xml
    dest: "{{ tomcat7_home }}/conf/server.xml"
  notify: restart tomcat
  become: yes

- name: template tomcat-users.xml
  template:
    src: tomcat-users.xml
    dest: "{{ tomcat7_home }}/conf/tomcat-users.xml"
    owner: tomcat
    group: tomcat
    mode: "640"
  notify: restart tomcat

