---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define tomcat7_home
  set_fact:
    tomcat7_home: "{{ __tomcat7_home }}"
  when: tomcat7_home is not defined

- name: Define tomcat7_version
  set_fact:
    tomcat7_version: "{{ __tomcat7_version }}"
  when:
    - tomcat7_version is not defined
    - __tomcat7_version is defined


- name: Define tomcat_target_dir
  set_fact:
    tomcat_target_dir: "{{ __tomcat7_target_dir }}"
  when:
    - tomcat7_target_dir is not defined
    - __tomcat7_target_dir is defined
