---

- name: Install Java 1.7
  apt:
    name: "{{ packages }}"
    state: present



# install tomcat

- name: example copying file with owner and permissions
  copy:
    src: /opt/apps/apache-tomcat-7.0.61.tar.gz
    dest: /opt/apache-tomcat-7.0.61.tar.gz
    owner: root
    group: root
    mode: 0644

- name: Extract archive
  command: chdir=/opt/ tar xzvf /opt/apache-tomcat-7.0.61.tar.gz -C /opt/ creates=/opt/apache-tomcat-7.0.61

- name: Simbolic link
  file:
    src: /opt/apache-tomcat-7.0.61
    path: "{{ __tomcat7_home }}"
    state: link
  become: yes

# /opt/apache-tomcat-7.0.61.tar.gz
# tar xvf /opt/apache-tomcat-7.0.61.tar.gz -C /opt/
# tar 추출 후 created folder           /opt/apache-tomcat-7.0.61

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home="{{ __tomcat7_home }}" createhome=no
  become: True
  become_method: sudo

- name: Change ownership of Tomcat installation
  file: path="{{ __tomcat7_home }}"  owner=tomcat group=tomcat state=directory recurse=yes

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/systemd/system/tomcat9.service.d
    state: directory
    mode: '0755'

- name: restart daemon service
  ansible.builtin.systemd:
    daemon_reload: yes
- name: start tomcat9
  service:
    name: tomcat9
    state: started