---
ㅊㅇ ㄴㅊ
- include: "define-home.yml"
  tags:
    - tomcat7
    - tomcat7-config
    - tomcat7-install

- include: "install-{{ ansible_os_family }}.yml"
  tags:
    - tomcat7
    - tomcat7-install

- include: config.yml
  when: "ansible_os_family == 'Debian'"
  tags:
    - tomcat7
    - tomcat7-config