---
- name: install backup agent
  command: rpm -ivh {{ __rpm_packages }}

## host file /etc/hosts 수정
- name: etc/hosts file update

- name: Insert configuration block
  lineinfile:
    path: "{{ item.path }}"
    backup: yes
    line: "{{ item.value }}"
  loop:
    - { path: /etc/pam.d/password-auth,  value:  }



- name:  Replace the etc/hosts
  replace:
    path: /etc/hosts
    regexp: "{{ item.before }}"
    replace:  "{{ item.after }}"
  loop:
    - { before: '# minlen = 9', after: 'minlen = 8' }


