---
- name: install backup agent
  command: rpm -ivh {{ __rpm_packages }}

## host file /etc/hosts 수정

- name: Insert configuration block
  lineinfile:
    path: "{{ item.path }}"
    backup: yes
    line: "{{ item.value }}"
  loop:
    - { path: /etc/hosts,  value: "{{ backup__hosts_file }}" }
    - { path: /etc/hosts,  value: "{{ backup__hosts_file }}" }


- name: Start Script
  command: /usr/local/avamar/etc/avagent.d/register "{{ backup_domain }}" /clients

- name: Service Start
  command: /etc/rc.d/init.d/avagent start
