---

# Include variables and define needed variables.
- name: Include variables
  include_vars:
    - logging.yml
    - security.yml
    - backup.yml

- name: Create a directory if it does not exist
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: yes
  loop:
    - /es
    - /backup_agent





- name:  Replace the hosts file
  become: yes
  replace:
    path: /etc/hosts
    regexp: "{{ item.before }}"
    replace:  "{{ item.after }}"
  loop:
    - { before: '#Banner none', after: 'Banner \/etc\/issue.net' }


