---

# Include variables and define needed variables.
- name: Include variables
  include_vars: "{{ item }}"
  loop:
    - logging.yml
    - security.yml
    - backup.yml

- name: Create a directory if it does not exist
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: yes
  loop:
    - /es
    - /backup_agent

- name: echo variable
  command: echo "{{ __src_tarfile }}"




