---

# Include variables and define needed variables.
- name: Include variables
  include_vars: "{{ item }}"
  loop:
    - logging.yml
    - security.yml
    - backup.yml

- name: Replace between the expressions (requires Ansible >= 2.4)
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}'
    replace: '172.10.10.10'





