---

# Include variables and define needed variables.
- name: Include variables
  include_vars: "{{ item }}"
  loop:
    - logging.yml
    - security.yml
    - backup.yml

- name: Add repository
  yum_repository:
    name: redhat
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
    enabled: no






