---

# Include variables and define needed variables.
- name: Include variables
  include_vars: "{{ item }}"
  loop:
    - logging.yml
    - security.yml
    - backup.yml

- name: Replace between the expressions (requires Ansible >= 2.4)
  ansible.builtin.replace:
    path: /etc/hosts
    after: '<VirtualHost [*]>'
    before: '</VirtualHost>'
    regexp: '^(.+)$'
    replace: '# \1'





