---
## 백신 설치
- name: Copying vaccine
  unarchive:
    src: "{{ security__src_tarfile }}"
    dest: /
    copy: yes
    owner: root
    group: root
    mode: 0755

- name: Start Script
  command: ./AgentDeploymentScript.sh

## 로그세이버 설치
- name: Logsaver Copying and Unarchive
  unarchive:
    src: "{{ security__src_tarfile2 }}"
    dest: /
    copy: yes
    owner: root
    group: root
    mode: 0755

- name: Start Script
  command: ./logsaver/install.sh

### script 실행 시 install 간의 interupt 창 발생


- name: Tior Agent Copying and Unarchive
  unarchive:
    src: "{{ security__src_tarfile3 }}"
    dest: /
    copy: yes
    owner: root
    group: root
    mode: 0755

- name: Start Script
  command: ./tior_inst/install.sh

### Logsaver ,Tior agent 설치시
### interrupt 화면 생성시 해결방법 없음
### test 진행 예정
